<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();

        DB::table('cities')->insert(
            [
                ['id' => 1, 'province_id' => 1, 'name' => 'Bangued'],
                ['id' => 2, 'province_id' => 1, 'name' => 'Boliney'],
                ['id' => 3, 'province_id' => 1, 'name' => 'Bucay'],
                ['id' => 4, 'province_id' => 1, 'name' => 'Bucloc'],
                ['id' => 5, 'province_id' => 1, 'name' => 'Daguioman'],
                ['id' => 6, 'province_id' => 1, 'name' => 'Danglas'],
                ['id' => 7, 'province_id' => 1, 'name' => 'Dolores'],
                ['id' => 8, 'province_id' => 1, 'name' => 'La Paz'],
                ['id' => 9, 'province_id' => 1, 'name' => 'Lacub'],
                ['id' => 10, 'province_id' => 1, 'name' => 'Lagangilang'],
                ['id' => 11, 'province_id' => 1, 'name' => 'Lagayan'],
                ['id' => 12, 'province_id' => 1, 'name' => 'Langiden'],
                ['id' => 13, 'province_id' => 1, 'name' => 'Licuan-Baay'],
                ['id' => 14, 'province_id' => 1, 'name' => 'Luba'],
                ['id' => 15, 'province_id' => 1, 'name' => 'Malibcong'],
                ['id' => 16, 'province_id' => 1, 'name' => 'Manabo'],
                ['id' => 17, 'province_id' => 1, 'name' => 'Peñarrubia'],
                ['id' => 18, 'province_id' => 1, 'name' => 'Pidigan'],
                ['id' => 19, 'province_id' => 1, 'name' => 'Pilar'],
                ['id' => 20, 'province_id' => 1, 'name' => 'Sallapadan'],
                ['id' => 21, 'province_id' => 1, 'name' => 'San Isidro'],
                ['id' => 22, 'province_id' => 1, 'name' => 'San Juan'],
                ['id' => 23, 'province_id' => 1, 'name' => 'San Quintin'],
                ['id' => 24, 'province_id' => 1, 'name' => 'Tayum'],
                ['id' => 25, 'province_id' => 1, 'name' => 'Tineg'],
                ['id' => 26, 'province_id' => 1, 'name' => 'Tubo'],
                ['id' => 27, 'province_id' => 1, 'name' => 'Villaviciosa'],
                ['id' => 28, 'province_id' => 2, 'name' => 'Butuan City'],
                ['id' => 29, 'province_id' => 2, 'name' => 'Cabadbaran City'],
                ['id' => 30, 'province_id' => 2, 'name' => 'Buenavista'],
                ['id' => 31, 'province_id' => 2, 'name' => 'Carmen'],
                ['id' => 32, 'province_id' => 2, 'name' => 'Jabonga'],
                ['id' => 33, 'province_id' => 2, 'name' => 'Kitcharao'],
                ['id' => 34, 'province_id' => 2, 'name' => 'Las Nieves'],
                ['id' => 35, 'province_id' => 2, 'name' => 'Magallanes'],
                ['id' => 36, 'province_id' => 2, 'name' => 'Nasipit'],
                ['id' => 37, 'province_id' => 2, 'name' => 'Remedios T. Romualdez'],
                ['id' => 38, 'province_id' => 2, 'name' => 'Santiago'],
                ['id' => 39, 'province_id' => 2, 'name' => 'Tubay'],
                ['id' => 40, 'province_id' => 3, 'name' => 'Bayugan City'],
                ['id' => 41, 'province_id' => 3, 'name' => 'Bunawan'],
                ['id' => 42, 'province_id' => 3, 'name' => 'Esperanza'],
                ['id' => 43, 'province_id' => 3, 'name' => 'La Paz'],
                ['id' => 44, 'province_id' => 3, 'name' => 'Loreto'],
                ['id' => 45, 'province_id' => 3, 'name' => 'Prosperidad'],
                ['id' => 46, 'province_id' => 3, 'name' => 'Rosario'],
                ['id' => 47, 'province_id' => 3, 'name' => 'San Francisco'],
                ['id' => 48, 'province_id' => 3, 'name' => 'San Luis'],
                ['id' => 49, 'province_id' => 3, 'name' => 'Santa Josefa'],
                ['id' => 50, 'province_id' => 3, 'name' => 'Sibagat'],
                ['id' => 51, 'province_id' => 3, 'name' => 'Talacogon'],
                ['id' => 52, 'province_id' => 3, 'name' => 'Trento'],
                ['id' => 53, 'province_id' => 3, 'name' => 'Veruela'],
                ['id' => 54, 'province_id' => 4, 'name' => 'Altavas'],
                ['id' => 55, 'province_id' => 4, 'name' => 'Balete'],
                ['id' => 56, 'province_id' => 4, 'name' => 'Banga'],
                ['id' => 57, 'province_id' => 4, 'name' => 'Batan'],
                ['id' => 58, 'province_id' => 4, 'name' => 'Buruanga'],
                ['id' => 59, 'province_id' => 4, 'name' => 'Ibajay'],
                ['id' => 60, 'province_id' => 4, 'name' => 'Kalibo'],
                ['id' => 61, 'province_id' => 4, 'name' => 'Lezo'],
                ['id' => 62, 'province_id' => 4, 'name' => 'Libacao'],
                ['id' => 63, 'province_id' => 4, 'name' => 'Madalag'],
                ['id' => 64, 'province_id' => 4, 'name' => 'Makato'],
                ['id' => 65, 'province_id' => 4, 'name' => 'Malay'],
                ['id' => 66, 'province_id' => 4, 'name' => 'Malinao'],
                ['id' => 67, 'province_id' => 4, 'name' => 'Nabas'],
                ['id' => 68, 'province_id' => 4, 'name' => 'New Washington'],
                ['id' => 69, 'province_id' => 4, 'name' => 'Numancia'],
                ['id' => 70, 'province_id' => 4, 'name' => 'Tangalan'],
                ['id' => 71, 'province_id' => 5, 'name' => 'Legazpi City'],
                ['id' => 72, 'province_id' => 5, 'name' => 'Ligao City'],
                ['id' => 73, 'province_id' => 5, 'name' => 'Tabaco City'],
                ['id' => 74, 'province_id' => 5, 'name' => 'Bacacay'],
                ['id' => 75, 'province_id' => 5, 'name' => 'Camalig'],
                ['id' => 76, 'province_id' => 5, 'name' => 'Daraga'],
                ['id' => 77, 'province_id' => 5, 'name' => 'Guinobatan'],
                ['id' => 78, 'province_id' => 5, 'name' => 'Jovellar'],
                ['id' => 79, 'province_id' => 5, 'name' => 'Libon'],
                ['id' => 80, 'province_id' => 5, 'name' => 'Malilipot'],
                ['id' => 81, 'province_id' => 5, 'name' => 'Malinao'],
                ['id' => 82, 'province_id' => 5, 'name' => 'Manito'],
                ['id' => 83, 'province_id' => 5, 'name' => 'Oas'],
                ['id' => 84, 'province_id' => 5, 'name' => 'Pio Duran'],
                ['id' => 85, 'province_id' => 5, 'name' => 'Polangui'],
                ['id' => 86, 'province_id' => 5, 'name' => 'Rapu-Rapu'],
                ['id' => 87, 'province_id' => 5, 'name' => 'Santo Domingo'],
                ['id' => 88, 'province_id' => 5, 'name' => 'Tiwi'],
                ['id' => 89, 'province_id' => 6, 'name' => 'Anini-y'],
                ['id' => 90, 'province_id' => 6, 'name' => 'Barbaza'],
                ['id' => 91, 'province_id' => 6, 'name' => 'Belison'],
                ['id' => 92, 'province_id' => 6, 'name' => 'Bugasong'],
                ['id' => 93, 'province_id' => 6, 'name' => 'Caluya'],
                ['id' => 94, 'province_id' => 6, 'name' => 'Culasi'],
                ['id' => 95, 'province_id' => 6, 'name' => 'Hamtic'],
                ['id' => 96, 'province_id' => 6, 'name' => 'Laua-an'],
                ['id' => 97, 'province_id' => 6, 'name' => 'Libertad'],
                ['id' => 98, 'province_id' => 6, 'name' => 'Pandan'],
                ['id' => 99, 'province_id' => 6, 'name' => 'Patnongon'],
                ['id' => 100, 'province_id' => 6, 'name' => 'San Jose'],
                ['id' => 101, 'province_id' => 6, 'name' => 'San Remigio'],
                ['id' => 102, 'province_id' => 6, 'name' => 'Sebaste'],
                ['id' => 103, 'province_id' => 6, 'name' => 'Sibalom'],
                ['id' => 104, 'province_id' => 6, 'name' => 'Tibiao'],
                ['id' => 105, 'province_id' => 6, 'name' => 'Tobias Fornier'],
                ['id' => 106, 'province_id' => 6, 'name' => 'Valderrama'],
                ['id' => 107, 'province_id' => 7, 'name' => 'Calanasan'],
                ['id' => 108, 'province_id' => 7, 'name' => 'Conner'],
                ['id' => 109, 'province_id' => 7, 'name' => 'Flora'],
                ['id' => 110, 'province_id' => 7, 'name' => 'Kabugao'],
                ['id' => 111, 'province_id' => 7, 'name' => 'Luna'],
                ['id' => 112, 'province_id' => 7, 'name' => 'Pudtol'],
                ['id' => 113, 'province_id' => 7, 'name' => 'Santa Marcela'],
                ['id' => 114, 'province_id' => 8, 'name' => 'Baler'],
                ['id' => 115, 'province_id' => 8, 'name' => 'Casiguran'],
                ['id' => 116, 'province_id' => 8, 'name' => 'Dilasag'],
                ['id' => 117, 'province_id' => 8, 'name' => 'Dinalungan'],
                ['id' => 118, 'province_id' => 8, 'name' => 'Dingalan'],
                ['id' => 119, 'province_id' => 8, 'name' => 'Dipaculao'],
                ['id' => 120, 'province_id' => 8, 'name' => 'Maria Aurora'],
                ['id' => 121, 'province_id' => 8, 'name' => 'San Luis'],
                ['id' => 122, 'province_id' => 9, 'name' => 'Isabela City'],
                ['id' => 123, 'province_id' => 9, 'name' => 'Lamitan City'],
                ['id' => 124, 'province_id' => 9, 'name' => 'Akbar'],
                ['id' => 125, 'province_id' => 9, 'name' => 'Al-Barka'],
                ['id' => 126, 'province_id' => 9, 'name' => 'Hadji Mohammad Ajul'],
                ['id' => 127, 'province_id' => 9, 'name' => 'Hadji Muhtamad'],
                ['id' => 128, 'province_id' => 9, 'name' => 'Lantawan'],
                ['id' => 129, 'province_id' => 9, 'name' => 'Maluso'],
                ['id' => 130, 'province_id' => 9, 'name' => 'Sumisip'],
                ['id' => 131, 'province_id' => 9, 'name' => 'Tabuan-Lasa'],
                ['id' => 132, 'province_id' => 9, 'name' => 'Tipo-Tipo'],
                ['id' => 133, 'province_id' => 9, 'name' => 'Tuburan'],
                ['id' => 134, 'province_id' => 9, 'name' => 'Ungkaya Pukan'],
                ['id' => 135, 'province_id' => 10, 'name' => 'Balanga City'],
                ['id' => 136, 'province_id' => 10, 'name' => 'Abucay'],
                ['id' => 137, 'province_id' => 10, 'name' => 'Bagac'],
                ['id' => 138, 'province_id' => 10, 'name' => 'Dinalupihan'],
                ['id' => 139, 'province_id' => 10, 'name' => 'Hermosa'],
                ['id' => 140, 'province_id' => 10, 'name' => 'Limay'],
                ['id' => 141, 'province_id' => 10, 'name' => 'Mariveles'],
                ['id' => 142, 'province_id' => 10, 'name' => 'Morong'],
                ['id' => 143, 'province_id' => 10, 'name' => 'Orani'],
                ['id' => 144, 'province_id' => 10, 'name' => 'Orion'],
                ['id' => 145, 'province_id' => 10, 'name' => 'Pilar'],
                ['id' => 146, 'province_id' => 10, 'name' => 'Samal'],
                ['id' => 147, 'province_id' => 11, 'name' => 'Basco'],
                ['id' => 148, 'province_id' => 11, 'name' => 'Itbayat'],
                ['id' => 149, 'province_id' => 11, 'name' => 'Ivana'],
                ['id' => 150, 'province_id' => 11, 'name' => 'Mahatao'],
                ['id' => 151, 'province_id' => 11, 'name' => 'Sabtang'],
                ['id' => 152, 'province_id' => 11, 'name' => 'Uyugan'],
                ['id' => 153, 'province_id' => 12, 'name' => 'Batangas City'],
                ['id' => 154, 'province_id' => 12, 'name' => 'Lipa City'],
                ['id' => 155, 'province_id' => 12, 'name' => 'Tanauan City'],
                ['id' => 156, 'province_id' => 12, 'name' => 'Agoncillo'],
                ['id' => 157, 'province_id' => 12, 'name' => 'Alitagtag'],
                ['id' => 158, 'province_id' => 12, 'name' => 'Balayan'],
                ['id' => 159, 'province_id' => 12, 'name' => 'Balete'],
                ['id' => 160, 'province_id' => 12, 'name' => 'Bauan'],
                ['id' => 161, 'province_id' => 12, 'name' => 'Calaca'],
                ['id' => 162, 'province_id' => 12, 'name' => 'Calatagan'],
                ['id' => 163, 'province_id' => 12, 'name' => 'Cuenca'],
                ['id' => 164, 'province_id' => 12, 'name' => 'Ibaan'],
                ['id' => 165, 'province_id' => 12, 'name' => 'Laurel'],
                ['id' => 166, 'province_id' => 12, 'name' => 'Lemery'],
                ['id' => 167, 'province_id' => 12, 'name' => 'Lian'],
                ['id' => 168, 'province_id' => 12, 'name' => 'Lobo'],
                ['id' => 169, 'province_id' => 12, 'name' => 'Mabini'],
                ['id' => 170, 'province_id' => 12, 'name' => 'Malvar'],
                ['id' => 171, 'province_id' => 12, 'name' => 'Mataas na Kahoy'],
                ['id' => 172, 'province_id' => 12, 'name' => 'Nasugbu'],
                ['id' => 173, 'province_id' => 12, 'name' => 'Padre Garcia'],
                ['id' => 174, 'province_id' => 12, 'name' => 'Rosario'],
                ['id' => 175, 'province_id' => 12, 'name' => 'San Jose'],
                ['id' => 176, 'province_id' => 12, 'name' => 'San Juan'],
                ['id' => 177, 'province_id' => 12, 'name' => 'San Luis'],
                ['id' => 178, 'province_id' => 12, 'name' => 'San Nicolas'],
                ['id' => 179, 'province_id' => 12, 'name' => 'San Pascual'],
                ['id' => 180, 'province_id' => 12, 'name' => 'Santa Teresita'],
                ['id' => 181, 'province_id' => 12, 'name' => 'Santo Tomas'],
                ['id' => 182, 'province_id' => 12, 'name' => 'Taal'],
                ['id' => 183, 'province_id' => 12, 'name' => 'Talisay'],
                ['id' => 184, 'province_id' => 12, 'name' => 'Taysan'],
                ['id' => 185, 'province_id' => 12, 'name' => 'Tingloy'],
                ['id' => 186, 'province_id' => 12, 'name' => 'Tuy'],
                ['id' => 187, 'province_id' => 13, 'name' => 'Baguio City'],
                ['id' => 188, 'province_id' => 13, 'name' => 'Atok'],
                ['id' => 189, 'province_id' => 13, 'name' => 'Bakun'],
                ['id' => 190, 'province_id' => 13, 'name' => 'Bokod'],
                ['id' => 191, 'province_id' => 13, 'name' => 'Buguias'],
                ['id' => 192, 'province_id' => 13, 'name' => 'Itogon'],
                ['id' => 193, 'province_id' => 13, 'name' => 'Kabayan'],
                ['id' => 194, 'province_id' => 13, 'name' => 'Kapangan'],
                ['id' => 195, 'province_id' => 13, 'name' => 'Kibungan'],
                ['id' => 196, 'province_id' => 13, 'name' => 'La Trinidad'],
                ['id' => 197, 'province_id' => 13, 'name' => 'Mankayan'],
                ['id' => 198, 'province_id' => 13, 'name' => 'Sablan'],
                ['id' => 199, 'province_id' => 13, 'name' => 'Tuba'],
                ['id' => 200, 'province_id' => 13, 'name' => 'Tublay'],
                ['id' => 201, 'province_id' => 14, 'name' => 'Almeria'],
                ['id' => 202, 'province_id' => 14, 'name' => 'Biliran'],
                ['id' => 203, 'province_id' => 14, 'name' => 'Cabucgayan'],
                ['id' => 204, 'province_id' => 14, 'name' => 'Caibiran'],
                ['id' => 205, 'province_id' => 14, 'name' => 'Culaba'],
                ['id' => 206, 'province_id' => 14, 'name' => 'Kawayan'],
                ['id' => 207, 'province_id' => 14, 'name' => 'Maripipi'],
                ['id' => 208, 'province_id' => 14, 'name' => 'Naval'],
                ['id' => 209, 'province_id' => 15, 'name' => 'Tagbilaran City'],
                ['id' => 210, 'province_id' => 15, 'name' => 'Alburquerque'],
                ['id' => 211, 'province_id' => 15, 'name' => 'Alicia'],
                ['id' => 212, 'province_id' => 15, 'name' => 'Anda'],
                ['id' => 213, 'province_id' => 15, 'name' => 'Antequera'],
                ['id' => 214, 'province_id' => 15, 'name' => 'Baclayon'],
                ['id' => 215, 'province_id' => 15, 'name' => 'Balilihan'],
                ['id' => 216, 'province_id' => 15, 'name' => 'Batuan'],
                ['id' => 217, 'province_id' => 15, 'name' => 'Bien Unido'],
                ['id' => 218, 'province_id' => 15, 'name' => 'Bilar'],
                ['id' => 219, 'province_id' => 15, 'name' => 'Buenavista'],
                ['id' => 220, 'province_id' => 15, 'name' => 'Calape'],
                ['id' => 221, 'province_id' => 15, 'name' => 'Candijay'],
                ['id' => 222, 'province_id' => 15, 'name' => 'Carmen'],
                ['id' => 223, 'province_id' => 15, 'name' => 'Catigbian'],
                ['id' => 224, 'province_id' => 15, 'name' => 'Clarin'],
                ['id' => 225, 'province_id' => 15, 'name' => 'Corella'],
                ['id' => 226, 'province_id' => 15, 'name' => 'Cortes'],
                ['id' => 227, 'province_id' => 15, 'name' => 'Dagohoy'],
                ['id' => 228, 'province_id' => 15, 'name' => 'Danao'],
                ['id' => 229, 'province_id' => 15, 'name' => 'Dauis'],
                ['id' => 230, 'province_id' => 15, 'name' => 'Dimiao'],
                ['id' => 231, 'province_id' => 15, 'name' => 'Duero'],
                ['id' => 232, 'province_id' => 15, 'name' => 'Garcia Hernandez'],
                ['id' => 233, 'province_id' => 15, 'name' => 'Guindulman'],
                ['id' => 234, 'province_id' => 15, 'name' => 'Inabanga'],
                ['id' => 235, 'province_id' => 15, 'name' => 'Jagna'],
                ['id' => 236, 'province_id' => 15, 'name' => 'Jetafe'],
                ['id' => 237, 'province_id' => 15, 'name' => 'Lila'],
                ['id' => 238, 'province_id' => 15, 'name' => 'Loay'],
                ['id' => 239, 'province_id' => 15, 'name' => 'Loboc'],
                ['id' => 240, 'province_id' => 15, 'name' => 'Loon'],
                ['id' => 241, 'province_id' => 15, 'name' => 'Mabini'],
                ['id' => 242, 'province_id' => 15, 'name' => 'Maribojoc'],
                ['id' => 243, 'province_id' => 15, 'name' => 'Panglao'],
                ['id' => 244, 'province_id' => 15, 'name' => 'Pilar'],
                ['id' => 245, 'province_id' => 15, 'name' => 'Pres. Carlos P. Garcia'],
                ['id' => 246, 'province_id' => 15, 'name' => 'Sagbayan'],
                ['id' => 247, 'province_id' => 15, 'name' => 'San Isidro'],
                ['id' => 248, 'province_id' => 15, 'name' => 'San Miguel'],
                ['id' => 249, 'province_id' => 15, 'name' => 'Sevilla'],
                ['id' => 250, 'province_id' => 15, 'name' => 'Sierra Bullones'],
                ['id' => 251, 'province_id' => 15, 'name' => 'Sikatuna'],
                ['id' => 252, 'province_id' => 15, 'name' => 'Talibon'],
                ['id' => 253, 'province_id' => 15, 'name' => 'Trinidad'],
                ['id' => 254, 'province_id' => 15, 'name' => 'Tubigon'],
                ['id' => 255, 'province_id' => 15, 'name' => 'Ubay'],
                ['id' => 256, 'province_id' => 15, 'name' => 'Valencia'],
                ['id' => 257, 'province_id' => 16, 'name' => 'Malaybalay City'],
                ['id' => 258, 'province_id' => 16, 'name' => 'Valencia City'],
                ['id' => 259, 'province_id' => 16, 'name' => 'Baungon'],
                ['id' => 260, 'province_id' => 16, 'name' => 'Cabanglasan'],
                ['id' => 261, 'province_id' => 16, 'name' => 'Damulog'],
                ['id' => 262, 'province_id' => 16, 'name' => 'Dangcagan'],
                ['id' => 263, 'province_id' => 16, 'name' => 'Don Carlos'],
                ['id' => 264, 'province_id' => 16, 'name' => 'Impasug-Ong'],
                ['id' => 265, 'province_id' => 16, 'name' => 'Kadingilan'],
                ['id' => 266, 'province_id' => 16, 'name' => 'Kalilangan'],
                ['id' => 267, 'province_id' => 16, 'name' => 'Kibawe'],
                ['id' => 268, 'province_id' => 16, 'name' => 'Kitaotao'],
                ['id' => 269, 'province_id' => 16, 'name' => 'Lantapan'],
                ['id' => 270, 'province_id' => 16, 'name' => 'Libona'],
                ['id' => 271, 'province_id' => 16, 'name' => 'Malitbog'],
                ['id' => 272, 'province_id' => 16, 'name' => 'Manolo Fortich'],
                ['id' => 273, 'province_id' => 16, 'name' => 'Maramag'],
                ['id' => 274, 'province_id' => 16, 'name' => 'Pangantucan'],
                ['id' => 275, 'province_id' => 16, 'name' => 'Quezon'],
                ['id' => 276, 'province_id' => 16, 'name' => 'San Fernando'],
                ['id' => 277, 'province_id' => 16, 'name' => 'Sumilao'],
                ['id' => 278, 'province_id' => 16, 'name' => 'Talakag'],
                ['id' => 279, 'province_id' => 17, 'name' => 'Malolos City'],
                ['id' => 280, 'province_id' => 17, 'name' => 'Meycauayan City'],
                ['id' => 281, 'province_id' => 17, 'name' => 'San Jose del Monte City'],
                ['id' => 282, 'province_id' => 17, 'name' => 'Angat'],
                ['id' => 283, 'province_id' => 17, 'name' => 'Balagtas'],
                ['id' => 284, 'province_id' => 17, 'name' => 'Baliuag'],
                ['id' => 285, 'province_id' => 17, 'name' => 'Bocaue'],
                ['id' => 286, 'province_id' => 17, 'name' => 'Bulacan'],
                ['id' => 287, 'province_id' => 17, 'name' => 'Bustos'],
                ['id' => 288, 'province_id' => 17, 'name' => 'Calumpit'],
                ['id' => 289, 'province_id' => 17, 'name' => 'Doña Remedios Trinidad'],
                ['id' => 290, 'province_id' => 17, 'name' => 'Guiguinto'],
                ['id' => 291, 'province_id' => 17, 'name' => 'Hagonoy'],
                ['id' => 292, 'province_id' => 17, 'name' => 'Marilao'],
                ['id' => 293, 'province_id' => 17, 'name' => 'Norzagaray'],
                ['id' => 294, 'province_id' => 17, 'name' => 'Obando'],
                ['id' => 295, 'province_id' => 17, 'name' => 'Pandi'],
                ['id' => 296, 'province_id' => 17, 'name' => 'Paombong'],
                ['id' => 297, 'province_id' => 17, 'name' => 'Plaridel'],
                ['id' => 298, 'province_id' => 17, 'name' => 'Pulilan'],
                ['id' => 299, 'province_id' => 17, 'name' => 'San Ildefonso'],
                ['id' => 300, 'province_id' => 17, 'name' => 'San Miguel'],
                ['id' => 301, 'province_id' => 17, 'name' => 'San Rafael'],
                ['id' => 302, 'province_id' => 17, 'name' => 'Santa Maria'],
                ['id' => 303, 'province_id' => 18, 'name' => 'Tuguegarao City'],
                ['id' => 304, 'province_id' => 18, 'name' => 'Abulug'],
                ['id' => 305, 'province_id' => 18, 'name' => 'Alcala'],
                ['id' => 306, 'province_id' => 18, 'name' => 'Allacapan'],
                ['id' => 307, 'province_id' => 18, 'name' => 'Amulung'],
                ['id' => 308, 'province_id' => 18, 'name' => 'Aparri'],
                ['id' => 309, 'province_id' => 18, 'name' => 'Baggao'],
                ['id' => 310, 'province_id' => 18, 'name' => 'Ballesteros'],
                ['id' => 311, 'province_id' => 18, 'name' => 'Buguey'],
                ['id' => 312, 'province_id' => 18, 'name' => 'Calayan'],
                ['id' => 313, 'province_id' => 18, 'name' => 'Camalaniugan'],
                ['id' => 314, 'province_id' => 18, 'name' => 'Claveria'],
                ['id' => 315, 'province_id' => 18, 'name' => 'Enrile'],
                ['id' => 316, 'province_id' => 18, 'name' => 'Gattaran'],
                ['id' => 317, 'province_id' => 18, 'name' => 'Gonzaga'],
                ['id' => 318, 'province_id' => 18, 'name' => 'Iguig'],
                ['id' => 319, 'province_id' => 18, 'name' => 'Lal-Lo'],
                ['id' => 320, 'province_id' => 18, 'name' => 'Lasam'],
                ['id' => 321, 'province_id' => 18, 'name' => 'Pamplona'],
                ['id' => 322, 'province_id' => 18, 'name' => 'Peñablanca'],
                ['id' => 323, 'province_id' => 18, 'name' => 'Piat'],
                ['id' => 324, 'province_id' => 18, 'name' => 'Rizal'],
                ['id' => 325, 'province_id' => 18, 'name' => 'Sanchez-Mira'],
                ['id' => 326, 'province_id' => 18, 'name' => 'Santa Ana'],
                ['id' => 327, 'province_id' => 18, 'name' => 'Santa Praxedes'],
                ['id' => 328, 'province_id' => 18, 'name' => 'Santa Teresita'],
                ['id' => 329, 'province_id' => 18, 'name' => 'Santo Niño'],
                ['id' => 330, 'province_id' => 18, 'name' => 'Solana'],
                ['id' => 331, 'province_id' => 18, 'name' => 'Tuao'],
                ['id' => 332, 'province_id' => 19, 'name' => 'Basud'],
                ['id' => 333, 'province_id' => 19, 'name' => 'Capalonga'],
                ['id' => 334, 'province_id' => 19, 'name' => 'Daet'],
                ['id' => 335, 'province_id' => 19, 'name' => 'Jose Panganiban'],
                ['id' => 336, 'province_id' => 19, 'name' => 'Labo'],
                ['id' => 337, 'province_id' => 19, 'name' => 'Mercedes'],
                ['id' => 338, 'province_id' => 19, 'name' => 'Paracale'],
                ['id' => 339, 'province_id' => 19, 'name' => 'San Lorenzo Ruiz'],
                ['id' => 340, 'province_id' => 19, 'name' => 'San Vicente'],
                ['id' => 341, 'province_id' => 19, 'name' => 'Santa Elena'],
                ['id' => 342, 'province_id' => 19, 'name' => 'Talisay'],
                ['id' => 343, 'province_id' => 19, 'name' => 'Vinzons'],
                ['id' => 344, 'province_id' => 20, 'name' => 'Iriga City'],
                ['id' => 345, 'province_id' => 20, 'name' => 'Naga City'],
                ['id' => 346, 'province_id' => 20, 'name' => 'Baao'],
                ['id' => 347, 'province_id' => 20, 'name' => 'Balatan'],
                ['id' => 348, 'province_id' => 20, 'name' => 'Bato'],
                ['id' => 349, 'province_id' => 20, 'name' => 'Bombon'],
                ['id' => 350, 'province_id' => 20, 'name' => 'Buhi'],
                ['id' => 351, 'province_id' => 20, 'name' => 'Bula'],
                ['id' => 352, 'province_id' => 20, 'name' => 'Cabusao'],
                ['id' => 353, 'province_id' => 20, 'name' => 'Calabanga'],
                ['id' => 354, 'province_id' => 20, 'name' => 'Camaligan'],
                ['id' => 355, 'province_id' => 20, 'name' => 'Canaman'],
                ['id' => 356, 'province_id' => 20, 'name' => 'Caramoan'],
                ['id' => 357, 'province_id' => 20, 'name' => 'Del Gallego'],
                ['id' => 358, 'province_id' => 20, 'name' => 'Gainza'],
                ['id' => 359, 'province_id' => 20, 'name' => 'Garchitorena'],
                ['id' => 360, 'province_id' => 20, 'name' => 'Goa'],
                ['id' => 361, 'province_id' => 20, 'name' => 'Lagonoy'],
                ['id' => 362, 'province_id' => 20, 'name' => 'Libmanan'],
                ['id' => 363, 'province_id' => 20, 'name' => 'Lupi'],
                ['id' => 364, 'province_id' => 20, 'name' => 'Magarao'],
                ['id' => 365, 'province_id' => 20, 'name' => 'Milaor'],
                ['id' => 366, 'province_id' => 20, 'name' => 'Minalabac'],
                ['id' => 367, 'province_id' => 20, 'name' => 'Nabua'],
                ['id' => 368, 'province_id' => 20, 'name' => 'Ocampo'],
                ['id' => 369, 'province_id' => 20, 'name' => 'Pamplona'],
                ['id' => 370, 'province_id' => 20, 'name' => 'Pasacao'],
                ['id' => 371, 'province_id' => 20, 'name' => 'Pili'],
                ['id' => 372, 'province_id' => 20, 'name' => 'Presentacion'],
                ['id' => 373, 'province_id' => 20, 'name' => 'Ragay'],
                ['id' => 374, 'province_id' => 20, 'name' => 'Sagñay'],
                ['id' => 375, 'province_id' => 20, 'name' => 'San Fernando'],
                ['id' => 376, 'province_id' => 20, 'name' => 'San Jose'],
                ['id' => 377, 'province_id' => 20, 'name' => 'Sipocot'],
                ['id' => 378, 'province_id' => 20, 'name' => 'Siruma'],
                ['id' => 379, 'province_id' => 20, 'name' => 'Tigaon'],
                ['id' => 380, 'province_id' => 20, 'name' => 'Tinambac'],
                ['id' => 381, 'province_id' => 21, 'name' => 'Catarman'],
                ['id' => 382, 'province_id' => 21, 'name' => 'Guinsiliban'],
                ['id' => 383, 'province_id' => 21, 'name' => 'Mahinog'],
                ['id' => 384, 'province_id' => 21, 'name' => 'Mambajao'],
                ['id' => 385, 'province_id' => 21, 'name' => 'Sagay'],
                ['id' => 386, 'province_id' => 22, 'name' => 'Roxas City'],
                ['id' => 387, 'province_id' => 22, 'name' => 'Cuartero'],
                ['id' => 388, 'province_id' => 22, 'name' => 'Dao'],
                ['id' => 389, 'province_id' => 22, 'name' => 'Dumalag'],
                ['id' => 390, 'province_id' => 22, 'name' => 'Dumarao'],
                ['id' => 391, 'province_id' => 22, 'name' => 'Ivisan'],
                ['id' => 392, 'province_id' => 22, 'name' => 'Jamindan'],
                ['id' => 393, 'province_id' => 22, 'name' => 'Ma-ayon'],
                ['id' => 394, 'province_id' => 22, 'name' => 'Mambusao'],
                ['id' => 395, 'province_id' => 22, 'name' => 'Panay'],
                ['id' => 396, 'province_id' => 22, 'name' => 'Panitan'],
                ['id' => 397, 'province_id' => 22, 'name' => 'Pilar'],
                ['id' => 398, 'province_id' => 22, 'name' => 'Pontevedra'],
                ['id' => 399, 'province_id' => 22, 'name' => 'President Roxas'],
                ['id' => 400, 'province_id' => 22, 'name' => 'Sapi-an'],
                ['id' => 401, 'province_id' => 22, 'name' => 'Sigma'],
                ['id' => 402, 'province_id' => 22, 'name' => 'Tapaz'],
                ['id' => 403, 'province_id' => 23, 'name' => 'Bagamanoc'],
                ['id' => 404, 'province_id' => 23, 'name' => 'Baras'],
                ['id' => 405, 'province_id' => 23, 'name' => 'Bato'],
                ['id' => 406, 'province_id' => 23, 'name' => 'Caramoran'],
                ['id' => 407, 'province_id' => 23, 'name' => 'Gigmoto'],
                ['id' => 408, 'province_id' => 23, 'name' => 'Pandan'],
                ['id' => 409, 'province_id' => 23, 'name' => 'Panganiban'],
                ['id' => 410, 'province_id' => 23, 'name' => 'San Andres'],
                ['id' => 411, 'province_id' => 23, 'name' => 'San Miguel'],
                ['id' => 412, 'province_id' => 23, 'name' => 'Viga'],
                ['id' => 413, 'province_id' => 23, 'name' => 'Virac'],
                ['id' => 414, 'province_id' => 24, 'name' => 'Cavite City'],
                ['id' => 415, 'province_id' => 24, 'name' => 'Dasmariñas City'],
                ['id' => 416, 'province_id' => 24, 'name' => 'Tagaytay City'],
                ['id' => 417, 'province_id' => 24, 'name' => 'Trece Martires City'],
                ['id' => 418, 'province_id' => 24, 'name' => 'Alfonso'],
                ['id' => 419, 'province_id' => 24, 'name' => 'Amadeo'],
                ['id' => 420, 'province_id' => 24, 'name' => 'Bacoor'],
                ['id' => 421, 'province_id' => 24, 'name' => 'Carmona'],
                ['id' => 422, 'province_id' => 24, 'name' => 'Gen. Mariano Alvarez'],
                ['id' => 423, 'province_id' => 24, 'name' => 'Gen. Emilio Aguinaldo'],
                ['id' => 424, 'province_id' => 24, 'name' => 'Gen. Trias'],
                ['id' => 425, 'province_id' => 24, 'name' => 'Imus'],
                ['id' => 426, 'province_id' => 24, 'name' => 'Indang'],
                ['id' => 427, 'province_id' => 24, 'name' => 'Kawit'],
                ['id' => 428, 'province_id' => 24, 'name' => 'Magallanes'],
                ['id' => 429, 'province_id' => 24, 'name' => 'Maragondon'],
                ['id' => 430, 'province_id' => 24, 'name' => 'Mendez'],
                ['id' => 431, 'province_id' => 24, 'name' => 'Naic'],
                ['id' => 432, 'province_id' => 24, 'name' => 'Noveleta'],
                ['id' => 433, 'province_id' => 24, 'name' => 'Rosario'],
                ['id' => 434, 'province_id' => 24, 'name' => 'Silang'],
                ['id' => 435, 'province_id' => 24, 'name' => 'Tanza'],
                ['id' => 436, 'province_id' => 24, 'name' => 'Ternate'],
                ['id' => 437, 'province_id' => 25, 'name' => 'Bogo City'],
                ['id' => 438, 'province_id' => 25, 'name' => 'Carcar City'],
                ['id' => 439, 'province_id' => 25, 'name' => 'Cebu City'],
                ['id' => 440, 'province_id' => 25, 'name' => 'Danao City'],
                ['id' => 441, 'province_id' => 25, 'name' => 'Lapu-Lapu City'],
                ['id' => 442, 'province_id' => 25, 'name' => 'Mandaue City'],
                ['id' => 443, 'province_id' => 25, 'name' => 'Naga City'],
                ['id' => 444, 'province_id' => 25, 'name' => 'Talisay City'],
                ['id' => 445, 'province_id' => 25, 'name' => 'Toledo City'],
                ['id' => 446, 'province_id' => 25, 'name' => 'Alcantara'],
                ['id' => 447, 'province_id' => 25, 'name' => 'Alcoy'],
                ['id' => 448, 'province_id' => 25, 'name' => 'Alegria'],
                ['id' => 449, 'province_id' => 25, 'name' => 'Aloguinsan'],
                ['id' => 450, 'province_id' => 25, 'name' => 'Argao'],
                ['id' => 451, 'province_id' => 25, 'name' => 'Asturias'],
                ['id' => 452, 'province_id' => 25, 'name' => 'Badian'],
                ['id' => 453, 'province_id' => 25, 'name' => 'Balamban'],
                ['id' => 454, 'province_id' => 25, 'name' => 'Bantayan'],
                ['id' => 455, 'province_id' => 25, 'name' => 'Barili'],
                ['id' => 456, 'province_id' => 25, 'name' => 'Boljoon'],
                ['id' => 457, 'province_id' => 25, 'name' => 'Borbon'],
                ['id' => 458, 'province_id' => 25, 'name' => 'Carmen'],
                ['id' => 459, 'province_id' => 25, 'name' => 'Catmon'],
                ['id' => 460, 'province_id' => 25, 'name' => 'Compostela'],
                ['id' => 461, 'province_id' => 25, 'name' => 'Consolacion'],
                ['id' => 462, 'province_id' => 25, 'name' => 'Cordoba'],
                ['id' => 463, 'province_id' => 25, 'name' => 'Daanbantayan'],
                ['id' => 464, 'province_id' => 25, 'name' => 'Dalaguete'],
                ['id' => 465, 'province_id' => 25, 'name' => 'Dumanjug'],
                ['id' => 466, 'province_id' => 25, 'name' => 'Ginatilan'],
                ['id' => 467, 'province_id' => 25, 'name' => 'Liloan'],
                ['id' => 468, 'province_id' => 25, 'name' => 'Madridejos'],
                ['id' => 469, 'province_id' => 25, 'name' => 'Malabuyoc'],
                ['id' => 470, 'province_id' => 25, 'name' => 'Medellin'],
                ['id' => 471, 'province_id' => 25, 'name' => 'Minglanilla'],
                ['id' => 472, 'province_id' => 25, 'name' => 'Moalboal'],
                ['id' => 473, 'province_id' => 25, 'name' => 'Oslob'],
                ['id' => 474, 'province_id' => 25, 'name' => 'Pilar'],
                ['id' => 475, 'province_id' => 25, 'name' => 'Pinamungahan'],
                ['id' => 476, 'province_id' => 25, 'name' => 'Poro'],
                ['id' => 477, 'province_id' => 25, 'name' => 'Ronda'],
                ['id' => 478, 'province_id' => 25, 'name' => 'Samboan'],
                ['id' => 479, 'province_id' => 25, 'name' => 'San Fernando'],
                ['id' => 480, 'province_id' => 25, 'name' => 'San Francisco'],
                ['id' => 481, 'province_id' => 25, 'name' => 'San Remigio'],
                ['id' => 482, 'province_id' => 25, 'name' => 'Santa Fe'],
                ['id' => 483, 'province_id' => 25, 'name' => 'Santander'],
                ['id' => 484, 'province_id' => 25, 'name' => 'Sibonga'],
                ['id' => 485, 'province_id' => 25, 'name' => 'Sogod'],
                ['id' => 486, 'province_id' => 25, 'name' => 'Tabogon'],
                ['id' => 487, 'province_id' => 25, 'name' => 'Tabuelan'],
                ['id' => 488, 'province_id' => 25, 'name' => 'Tuburan'],
                ['id' => 489, 'province_id' => 25, 'name' => 'Tudela'],
                ['id' => 490, 'province_id' => 26, 'name' => 'Compostela'],
                ['id' => 491, 'province_id' => 26, 'name' => 'Laak'],
                ['id' => 492, 'province_id' => 26, 'name' => 'Mabini'],
                ['id' => 493, 'province_id' => 26, 'name' => 'Maco'],
                ['id' => 494, 'province_id' => 26, 'name' => 'Maragusan'],
                ['id' => 495, 'province_id' => 26, 'name' => 'Mawab'],
                ['id' => 496, 'province_id' => 26, 'name' => 'Monkayo'],
                ['id' => 497, 'province_id' => 26, 'name' => 'Montevista'],
                ['id' => 498, 'province_id' => 26, 'name' => 'Nabunturan'],
                ['id' => 499, 'province_id' => 26, 'name' => 'New Bataan'],
                ['id' => 500, 'province_id' => 26, 'name' => 'Pantukan'],
                ['id' => 501, 'province_id' => 27, 'name' => 'Kidapawan City'],
                ['id' => 502, 'province_id' => 27, 'name' => 'Alamada'],
                ['id' => 503, 'province_id' => 27, 'name' => 'Aleosan'],
                ['id' => 504, 'province_id' => 27, 'name' => 'Antipas'],
                ['id' => 505, 'province_id' => 27, 'name' => 'Arakan'],
                ['id' => 506, 'province_id' => 27, 'name' => 'Banisilan'],
                ['id' => 507, 'province_id' => 27, 'name' => 'Carmen'],
                ['id' => 508, 'province_id' => 27, 'name' => 'Kabacan'],
                ['id' => 509, 'province_id' => 27, 'name' => 'Libungan'],
                ['id' => 510, 'province_id' => 27, 'name' => 'M\'Lang'],
                ['id' => 511, 'province_id' => 27, 'name' => 'Magpet'],
                ['id' => 512, 'province_id' => 27, 'name' => 'Makilala'],
                ['id' => 513, 'province_id' => 27, 'name' => 'Matalam'],
                ['id' => 514, 'province_id' => 27, 'name' => 'Midsayap'],
                ['id' => 515, 'province_id' => 27, 'name' => 'Pigkawayan'],
                ['id' => 516, 'province_id' => 27, 'name' => 'Pikit'],
                ['id' => 517, 'province_id' => 27, 'name' => 'President Roxas'],
                ['id' => 518, 'province_id' => 27, 'name' => 'Tulunan'],
                ['id' => 519, 'province_id' => 28, 'name' => 'Panabo City'],
                ['id' => 520, 'province_id' => 28, 'name' => 'Island Garden City of Samal'],
                ['id' => 521, 'province_id' => 28, 'name' => 'Tagum City'],
                ['id' => 522, 'province_id' => 28, 'name' => 'Asuncion'],
                ['id' => 523, 'province_id' => 28, 'name' => 'Braulio E. Dujali'],
                ['id' => 524, 'province_id' => 28, 'name' => 'Carmen'],
                ['id' => 525, 'province_id' => 28, 'name' => 'Kapalong'],
                ['id' => 526, 'province_id' => 28, 'name' => 'New Corella'],
                ['id' => 527, 'province_id' => 28, 'name' => 'San Isidro'],
                ['id' => 528, 'province_id' => 28, 'name' => 'Santo Tomas'],
                ['id' => 529, 'province_id' => 28, 'name' => 'Talaingod'],
                ['id' => 530, 'province_id' => 29, 'name' => 'Davao City'],
                ['id' => 531, 'province_id' => 29, 'name' => 'Digos City'],
                ['id' => 532, 'province_id' => 29, 'name' => 'Bansalan'],
                ['id' => 533, 'province_id' => 29, 'name' => 'Don Marcelino'],
                ['id' => 534, 'province_id' => 29, 'name' => 'Hagonoy'],
                ['id' => 535, 'province_id' => 29, 'name' => 'Jose Abad Santos'],
                ['id' => 536, 'province_id' => 29, 'name' => 'Kiblawan'],
                ['id' => 537, 'province_id' => 29, 'name' => 'Magsaysay'],
                ['id' => 538, 'province_id' => 29, 'name' => 'Malalag'],
                ['id' => 539, 'province_id' => 29, 'name' => 'Malita'],
                ['id' => 540, 'province_id' => 29, 'name' => 'Matanao'],
                ['id' => 541, 'province_id' => 29, 'name' => 'Padada'],
                ['id' => 542, 'province_id' => 29, 'name' => 'Santa Cruz'],
                ['id' => 543, 'province_id' => 29, 'name' => 'Santa Maria'],
                ['id' => 544, 'province_id' => 29, 'name' => 'Sarangani'],
                ['id' => 545, 'province_id' => 29, 'name' => 'Sulop'],
                ['id' => 546, 'province_id' => 30, 'name' => 'Mati City'],
                ['id' => 547, 'province_id' => 30, 'name' => 'Baganga'],
                ['id' => 548, 'province_id' => 30, 'name' => 'Banaybanay'],
                ['id' => 549, 'province_id' => 30, 'name' => 'Boston'],
                ['id' => 550, 'province_id' => 30, 'name' => 'Caraga'],
                ['id' => 551, 'province_id' => 30, 'name' => 'Cateel'],
                ['id' => 552, 'province_id' => 30, 'name' => 'Governor Generoso'],
                ['id' => 553, 'province_id' => 30, 'name' => 'Lupon'],
                ['id' => 554, 'province_id' => 30, 'name' => 'Manay'],
                ['id' => 555, 'province_id' => 30, 'name' => 'San Isidro'],
                ['id' => 556, 'province_id' => 30, 'name' => 'Tarragona'],
                ['id' => 557, 'province_id' => 31, 'name' => 'Basilisia [Rizal]'],
                ['id' => 558, 'province_id' => 31, 'name' => 'Cagdianao'],
                ['id' => 559, 'province_id' => 31, 'name' => 'Dinagat'],
                ['id' => 560, 'province_id' => 31, 'name' => 'Libjo [Albor]'],
                ['id' => 561, 'province_id' => 31, 'name' => 'Loreto'],
                ['id' => 562, 'province_id' => 31, 'name' => 'San Jose'],
                ['id' => 563, 'province_id' => 32, 'name' => 'Borongan City'],
                ['id' => 564, 'province_id' => 32, 'name' => 'Arteche'],
                ['id' => 565, 'province_id' => 32, 'name' => 'Balangiga'],
                ['id' => 566, 'province_id' => 32, 'name' => 'Balangkayan'],
                ['id' => 567, 'province_id' => 32, 'name' => 'Can-avid'],
                ['id' => 568, 'province_id' => 32, 'name' => 'Dolores'],
                ['id' => 569, 'province_id' => 32, 'name' => 'General MacArthur'],
                ['id' => 570, 'province_id' => 32, 'name' => 'Giporlos'],
                ['id' => 571, 'province_id' => 32, 'name' => 'Guiuan'],
                ['id' => 572, 'province_id' => 32, 'name' => 'Hernani'],
                ['id' => 573, 'province_id' => 32, 'name' => 'Jipapad'],
                ['id' => 574, 'province_id' => 32, 'name' => 'Lawaan'],
                ['id' => 575, 'province_id' => 32, 'name' => 'Llorente'],
                ['id' => 576, 'province_id' => 32, 'name' => 'Maslog'],
                ['id' => 577, 'province_id' => 32, 'name' => 'Maydolong'],
                ['id' => 578, 'province_id' => 32, 'name' => 'Mercedes'],
                ['id' => 579, 'province_id' => 32, 'name' => 'Oras'],
                ['id' => 580, 'province_id' => 32, 'name' => 'Quinapondan'],
                ['id' => 581, 'province_id' => 32, 'name' => 'Salcedo'],
                ['id' => 582, 'province_id' => 32, 'name' => 'San Julian'],
                ['id' => 583, 'province_id' => 32, 'name' => 'San Policarpo'],
                ['id' => 584, 'province_id' => 32, 'name' => 'Sulat'],
                ['id' => 585, 'province_id' => 32, 'name' => 'Taft'],
                ['id' => 586, 'province_id' => 33, 'name' => 'Buenavista'],
                ['id' => 587, 'province_id' => 33, 'name' => 'Jordan'],
                ['id' => 588, 'province_id' => 33, 'name' => 'Nueva Valencia'],
                ['id' => 589, 'province_id' => 33, 'name' => 'San Lorenzo'],
                ['id' => 590, 'province_id' => 33, 'name' => 'Sibunag'],
                ['id' => 591, 'province_id' => 34, 'name' => 'Aguinaldo'],
                ['id' => 592, 'province_id' => 34, 'name' => 'Alfonso Lista'],
                ['id' => 593, 'province_id' => 34, 'name' => 'Asipulo'],
                ['id' => 594, 'province_id' => 34, 'name' => 'Banaue'],
                ['id' => 595, 'province_id' => 34, 'name' => 'Hingyon'],
                ['id' => 596, 'province_id' => 34, 'name' => 'Hungduan'],
                ['id' => 597, 'province_id' => 34, 'name' => 'Kiangan'],
                ['id' => 598, 'province_id' => 34, 'name' => 'Lagawe'],
                ['id' => 599, 'province_id' => 34, 'name' => 'Lamut'],
                ['id' => 600, 'province_id' => 34, 'name' => 'Mayoyao'],
                ['id' => 601, 'province_id' => 34, 'name' => 'Tinoc'],
                ['id' => 602, 'province_id' => 35, 'name' => 'Batac City'],
                ['id' => 603, 'province_id' => 35, 'name' => 'Laoag City'],
                ['id' => 604, 'province_id' => 35, 'name' => 'Adams'],
                ['id' => 605, 'province_id' => 35, 'name' => 'Bacarra'],
                ['id' => 606, 'province_id' => 35, 'name' => 'Badoc'],
                ['id' => 607, 'province_id' => 35, 'name' => 'Bangui'],
                ['id' => 608, 'province_id' => 35, 'name' => 'Banna'],
                ['id' => 609, 'province_id' => 35, 'name' => 'Burgos'],
                ['id' => 610, 'province_id' => 35, 'name' => 'Carasi'],
                ['id' => 611, 'province_id' => 35, 'name' => 'Currimao'],
                ['id' => 612, 'province_id' => 35, 'name' => 'Dingras'],
                ['id' => 613, 'province_id' => 35, 'name' => 'Dumalneg'],
                ['id' => 614, 'province_id' => 35, 'name' => 'Marcos'],
                ['id' => 615, 'province_id' => 35, 'name' => 'Nueva Era'],
                ['id' => 616, 'province_id' => 35, 'name' => 'Pagudpud'],
                ['id' => 617, 'province_id' => 35, 'name' => 'Paoay'],
                ['id' => 618, 'province_id' => 35, 'name' => 'Pasuquin'],
                ['id' => 619, 'province_id' => 35, 'name' => 'Piddig'],
                ['id' => 620, 'province_id' => 35, 'name' => 'Pinili'],
                ['id' => 621, 'province_id' => 35, 'name' => 'San Nicolas'],
                ['id' => 622, 'province_id' => 35, 'name' => 'Sarrat'],
                ['id' => 623, 'province_id' => 35, 'name' => 'Solsona'],
                ['id' => 624, 'province_id' => 35, 'name' => 'Vintar'],
                ['id' => 625, 'province_id' => 36, 'name' => 'Candon City'],
                ['id' => 626, 'province_id' => 36, 'name' => 'Vigan City'],
                ['id' => 627, 'province_id' => 36, 'name' => 'Alilem'],
                ['id' => 628, 'province_id' => 36, 'name' => 'Banayoyo'],
                ['id' => 629, 'province_id' => 36, 'name' => 'Bantay'],
                ['id' => 630, 'province_id' => 36, 'name' => 'Burgos'],
                ['id' => 631, 'province_id' => 36, 'name' => 'Cabugao'],
                ['id' => 632, 'province_id' => 36, 'name' => 'Caoayan'],
                ['id' => 633, 'province_id' => 36, 'name' => 'Cervantes'],
                ['id' => 634, 'province_id' => 36, 'name' => 'Galimuyod'],
                ['id' => 635, 'province_id' => 36, 'name' => 'Gregorio Del Pilar'],
                ['id' => 636, 'province_id' => 36, 'name' => 'Lidlidda'],
                ['id' => 637, 'province_id' => 36, 'name' => 'Magsingal'],
                ['id' => 638, 'province_id' => 36, 'name' => 'Nagbukel'],
                ['id' => 639, 'province_id' => 36, 'name' => 'Narvacan'],
                ['id' => 640, 'province_id' => 36, 'name' => 'Quirino'],
                ['id' => 641, 'province_id' => 36, 'name' => 'Salcedo'],
                ['id' => 642, 'province_id' => 36, 'name' => 'San Emilio'],
                ['id' => 643, 'province_id' => 36, 'name' => 'San Esteban'],
                ['id' => 644, 'province_id' => 36, 'name' => 'San Ildefonso'],
                ['id' => 645, 'province_id' => 36, 'name' => 'San Juan'],
                ['id' => 646, 'province_id' => 36, 'name' => 'San Vicente'],
                ['id' => 647, 'province_id' => 36, 'name' => 'Santa'],
                ['id' => 648, 'province_id' => 36, 'name' => 'Santa Catalina'],
                ['id' => 649, 'province_id' => 36, 'name' => 'Santa Cruz'],
                ['id' => 650, 'province_id' => 36, 'name' => 'Santa Lucia'],
                ['id' => 651, 'province_id' => 36, 'name' => 'Santa Maria'],
                ['id' => 652, 'province_id' => 36, 'name' => 'Santiago'],
                ['id' => 653, 'province_id' => 36, 'name' => 'Santo Domingo'],
                ['id' => 654, 'province_id' => 36, 'name' => 'Sigay'],
                ['id' => 655, 'province_id' => 36, 'name' => 'Sinait'],
                ['id' => 656, 'province_id' => 36, 'name' => 'Sugpon'],
                ['id' => 657, 'province_id' => 36, 'name' => 'Suyo'],
                ['id' => 658, 'province_id' => 36, 'name' => 'Tagudin'],
                ['id' => 659, 'province_id' => 37, 'name' => 'Cauayan City'],
                ['id' => 660, 'province_id' => 37, 'name' => 'Santiago City'],
                ['id' => 661, 'province_id' => 37, 'name' => 'Alicia'],
                ['id' => 662, 'province_id' => 37, 'name' => 'Angadanan'],
                ['id' => 663, 'province_id' => 37, 'name' => 'Aurora'],
                ['id' => 664, 'province_id' => 37, 'name' => 'Benito Soliven'],
                ['id' => 665, 'province_id' => 37, 'name' => 'Burgos'],
                ['id' => 666, 'province_id' => 37, 'name' => 'Cabagan'],
                ['id' => 667, 'province_id' => 37, 'name' => 'Cabatuan'],
                ['id' => 668, 'province_id' => 37, 'name' => 'Cordon'],
                ['id' => 669, 'province_id' => 37, 'name' => 'Delfin Albano'],
                ['id' => 670, 'province_id' => 37, 'name' => 'Dinapigue'],
                ['id' => 671, 'province_id' => 37, 'name' => 'Divilacan'],
                ['id' => 672, 'province_id' => 37, 'name' => 'Echague'],
                ['id' => 673, 'province_id' => 37, 'name' => 'Gamu'],
                ['id' => 674, 'province_id' => 37, 'name' => 'Ilagan'],
                ['id' => 675, 'province_id' => 37, 'name' => 'Jones'],
                ['id' => 676, 'province_id' => 37, 'name' => 'Luna'],
                ['id' => 677, 'province_id' => 37, 'name' => 'Maconacon'],
                ['id' => 678, 'province_id' => 37, 'name' => 'Mallig'],
                ['id' => 679, 'province_id' => 37, 'name' => 'Naguilian'],
                ['id' => 680, 'province_id' => 37, 'name' => 'Palanan'],
                ['id' => 681, 'province_id' => 37, 'name' => 'Quezon'],
                ['id' => 682, 'province_id' => 37, 'name' => 'Quirino'],
                ['id' => 683, 'province_id' => 37, 'name' => 'Ramon'],
                ['id' => 684, 'province_id' => 37, 'name' => 'Reina Mercedes'],
                ['id' => 685, 'province_id' => 37, 'name' => 'Roxas'],
                ['id' => 686, 'province_id' => 37, 'name' => 'San Agustin'],
                ['id' => 687, 'province_id' => 37, 'name' => 'San Guillermo'],
                ['id' => 688, 'province_id' => 37, 'name' => 'San Isidro'],
                ['id' => 689, 'province_id' => 37, 'name' => 'San Manuel'],
                ['id' => 690, 'province_id' => 37, 'name' => 'San Mariano'],
                ['id' => 691, 'province_id' => 37, 'name' => 'San Mateo'],
                ['id' => 692, 'province_id' => 37, 'name' => 'San Pablo'],
                ['id' => 693, 'province_id' => 37, 'name' => 'Santa Maria'],
                ['id' => 694, 'province_id' => 37, 'name' => 'Santo Tomas'],
                ['id' => 695, 'province_id' => 37, 'name' => 'Tumauini'],
                ['id' => 696, 'province_id' => 38, 'name' => 'Iloilo City'],
                ['id' => 697, 'province_id' => 38, 'name' => 'Passi City'],
                ['id' => 698, 'province_id' => 38, 'name' => 'Ajuy'],
                ['id' => 699, 'province_id' => 38, 'name' => 'Alimodian'],
                ['id' => 700, 'province_id' => 38, 'name' => 'Anilao'],
                ['id' => 701, 'province_id' => 38, 'name' => 'Badiangan'],
                ['id' => 702, 'province_id' => 38, 'name' => 'Balasan'],
                ['id' => 703, 'province_id' => 38, 'name' => 'Banate'],
                ['id' => 704, 'province_id' => 38, 'name' => 'Barotac Nuevo'],
                ['id' => 705, 'province_id' => 38, 'name' => 'Barotac Viejo'],
                ['id' => 706, 'province_id' => 38, 'name' => 'Batad'],
                ['id' => 707, 'province_id' => 38, 'name' => 'Bingawan'],
                ['id' => 708, 'province_id' => 38, 'name' => 'Cabatuan'],
                ['id' => 709, 'province_id' => 38, 'name' => 'Calinog'],
                ['id' => 710, 'province_id' => 38, 'name' => 'Carles'],
                ['id' => 711, 'province_id' => 38, 'name' => 'Concepcion'],
                ['id' => 712, 'province_id' => 38, 'name' => 'Dingle'],
                ['id' => 713, 'province_id' => 38, 'name' => 'Dueñas'],
                ['id' => 714, 'province_id' => 38, 'name' => 'Dumangas'],
                ['id' => 715, 'province_id' => 38, 'name' => 'Estancia'],
                ['id' => 716, 'province_id' => 38, 'name' => 'Guimbal'],
                ['id' => 717, 'province_id' => 38, 'name' => 'Igbaras'],
                ['id' => 718, 'province_id' => 38, 'name' => 'Janiuay'],
                ['id' => 719, 'province_id' => 38, 'name' => 'Lambunao'],
                ['id' => 720, 'province_id' => 38, 'name' => 'Leganes'],
                ['id' => 721, 'province_id' => 38, 'name' => 'Lemery'],
                ['id' => 722, 'province_id' => 38, 'name' => 'Leon'],
                ['id' => 723, 'province_id' => 38, 'name' => 'Maasin'],
                ['id' => 724, 'province_id' => 38, 'name' => 'Miagao'],
                ['id' => 725, 'province_id' => 38, 'name' => 'Mina'],
                ['id' => 726, 'province_id' => 38, 'name' => 'New Lucena'],
                ['id' => 727, 'province_id' => 38, 'name' => 'Oton'],
                ['id' => 728, 'province_id' => 38, 'name' => 'Pavia'],
                ['id' => 729, 'province_id' => 38, 'name' => 'Pototan'],
                ['id' => 730, 'province_id' => 38, 'name' => 'San Dionisio'],
                ['id' => 731, 'province_id' => 38, 'name' => 'San Enrique'],
                ['id' => 732, 'province_id' => 38, 'name' => 'San Joaquin'],
                ['id' => 733, 'province_id' => 38, 'name' => 'San Miguel'],
                ['id' => 734, 'province_id' => 38, 'name' => 'San Rafael'],
                ['id' => 735, 'province_id' => 38, 'name' => 'Santa Barbara'],
                ['id' => 736, 'province_id' => 38, 'name' => 'Sara'],
                ['id' => 737, 'province_id' => 38, 'name' => 'Tigbauan'],
                ['id' => 738, 'province_id' => 38, 'name' => 'Tubungan'],
                ['id' => 739, 'province_id' => 38, 'name' => 'Zarraga'],
                ['id' => 740, 'province_id' => 39, 'name' => 'Tabuk City'],
                ['id' => 741, 'province_id' => 39, 'name' => 'Balbalan'],
                ['id' => 742, 'province_id' => 39, 'name' => 'Lubuagan'],
                ['id' => 743, 'province_id' => 39, 'name' => 'Pasil'],
                ['id' => 744, 'province_id' => 39, 'name' => 'Pinukpuk'],
                ['id' => 745, 'province_id' => 39, 'name' => 'Rizal'],
                ['id' => 746, 'province_id' => 39, 'name' => 'Tanudan'],
                ['id' => 747, 'province_id' => 39, 'name' => 'Tinglayan'],
                ['id' => 748, 'province_id' => 40, 'name' => 'San Fernando City'],
                ['id' => 749, 'province_id' => 40, 'name' => 'Agoo'],
                ['id' => 750, 'province_id' => 40, 'name' => 'Aringay'],
                ['id' => 751, 'province_id' => 40, 'name' => 'Bacnotan'],
                ['id' => 752, 'province_id' => 40, 'name' => 'Bagulin'],
                ['id' => 753, 'province_id' => 40, 'name' => 'Balaoan'],
                ['id' => 754, 'province_id' => 40, 'name' => 'Bangar'],
                ['id' => 755, 'province_id' => 40, 'name' => 'Bauang'],
                ['id' => 756, 'province_id' => 40, 'name' => 'Burgos'],
                ['id' => 757, 'province_id' => 40, 'name' => 'Caba'],
                ['id' => 758, 'province_id' => 40, 'name' => 'Luna'],
                ['id' => 759, 'province_id' => 40, 'name' => 'Naguilian'],
                ['id' => 760, 'province_id' => 40, 'name' => 'Pugo'],
                ['id' => 761, 'province_id' => 40, 'name' => 'Rosario'],
                ['id' => 762, 'province_id' => 40, 'name' => 'San Gabriel'],
                ['id' => 763, 'province_id' => 40, 'name' => 'San Juan'],
                ['id' => 764, 'province_id' => 40, 'name' => 'Santo Tomas'],
                ['id' => 765, 'province_id' => 40, 'name' => 'Santol'],
                ['id' => 766, 'province_id' => 40, 'name' => 'Sudipen'],
                ['id' => 767, 'province_id' => 40, 'name' => 'Tubao'],
                ['id' => 768, 'province_id' => 41, 'name' => 'Calamba City'],
                ['id' => 769, 'province_id' => 41, 'name' => 'San Pablo City'],
                ['id' => 770, 'province_id' => 41, 'name' => 'Santa Rosa City'],
                ['id' => 771, 'province_id' => 41, 'name' => 'Alaminos'],
                ['id' => 772, 'province_id' => 41, 'name' => 'Bay'],
                ['id' => 773, 'province_id' => 41, 'name' => 'Biñan'],
                ['id' => 774, 'province_id' => 41, 'name' => 'Cabuyao'],
                ['id' => 775, 'province_id' => 41, 'name' => 'Calauan'],
                ['id' => 776, 'province_id' => 41, 'name' => 'Cavinti'],
                ['id' => 777, 'province_id' => 41, 'name' => 'Famy'],
                ['id' => 778, 'province_id' => 41, 'name' => 'Kalayaan'],
                ['id' => 779, 'province_id' => 41, 'name' => 'Liliw'],
                ['id' => 780, 'province_id' => 41, 'name' => 'Los Baños'],
                ['id' => 781, 'province_id' => 41, 'name' => 'Luisiana'],
                ['id' => 782, 'province_id' => 41, 'name' => 'Lumban'],
                ['id' => 783, 'province_id' => 41, 'name' => 'Mabitac'],
                ['id' => 784, 'province_id' => 41, 'name' => 'Magdalena'],
                ['id' => 785, 'province_id' => 41, 'name' => 'Majayjay'],
                ['id' => 786, 'province_id' => 41, 'name' => 'Nagcarlan'],
                ['id' => 787, 'province_id' => 41, 'name' => 'Paete'],
                ['id' => 788, 'province_id' => 41, 'name' => 'Pagsanjan'],
                ['id' => 789, 'province_id' => 41, 'name' => 'Pakil'],
                ['id' => 790, 'province_id' => 41, 'name' => 'Pangil'],
                ['id' => 791, 'province_id' => 41, 'name' => 'Pila'],
                ['id' => 792, 'province_id' => 41, 'name' => 'Rizal'],
                ['id' => 793, 'province_id' => 41, 'name' => 'San Pedro'],
                ['id' => 794, 'province_id' => 41, 'name' => 'Santa Cruz'],
                ['id' => 795, 'province_id' => 41, 'name' => 'Santa Maria'],
                ['id' => 796, 'province_id' => 41, 'name' => 'Siniloan'],
                ['id' => 797, 'province_id' => 41, 'name' => 'Victoria'],
                ['id' => 798, 'province_id' => 42, 'name' => 'Iligan City'],
                ['id' => 799, 'province_id' => 42, 'name' => 'Bacolod'],
                ['id' => 800, 'province_id' => 42, 'name' => 'Baloi'],
                ['id' => 801, 'province_id' => 42, 'name' => 'Baroy'],
                ['id' => 802, 'province_id' => 42, 'name' => 'Kapatagan'],
                ['id' => 803, 'province_id' => 42, 'name' => 'Kauswagan'],
                ['id' => 804, 'province_id' => 42, 'name' => 'Kolambugan'],
                ['id' => 805, 'province_id' => 42, 'name' => 'Lala'],
                ['id' => 806, 'province_id' => 42, 'name' => 'Linamon'],
                ['id' => 807, 'province_id' => 42, 'name' => 'Magsaysay'],
                ['id' => 808, 'province_id' => 42, 'name' => 'Maigo'],
                ['id' => 809, 'province_id' => 42, 'name' => 'Matungao'],
                ['id' => 810, 'province_id' => 42, 'name' => 'Munai'],
                ['id' => 811, 'province_id' => 42, 'name' => 'Nunungan'],
                ['id' => 812, 'province_id' => 42, 'name' => 'Pantao Ragat'],
                ['id' => 813, 'province_id' => 42, 'name' => 'Pantar'],
                ['id' => 814, 'province_id' => 42, 'name' => 'Poona Piagapo'],
                ['id' => 815, 'province_id' => 42, 'name' => 'Salvador'],
                ['id' => 816, 'province_id' => 42, 'name' => 'Sapad'],
                ['id' => 817, 'province_id' => 42, 'name' => 'Sultan Naga Dimaporo'],
                ['id' => 818, 'province_id' => 42, 'name' => 'Tagoloan'],
                ['id' => 819, 'province_id' => 42, 'name' => 'Tangcal'],
                ['id' => 820, 'province_id' => 42, 'name' => 'Tubod'],
                ['id' => 821, 'province_id' => 43, 'name' => 'Marawi City'],
                ['id' => 822, 'province_id' => 43, 'name' => 'Bacolod-Kalawi'],
                ['id' => 823, 'province_id' => 43, 'name' => 'Balabagan'],
                ['id' => 824, 'province_id' => 43, 'name' => 'Balindong'],
                ['id' => 825, 'province_id' => 43, 'name' => 'Bayang'],
                ['id' => 826, 'province_id' => 43, 'name' => 'Binidayan'],
                ['id' => 827, 'province_id' => 43, 'name' => 'Buadiposo-Buntong'],
                ['id' => 828, 'province_id' => 43, 'name' => 'Bubong'],
                ['id' => 829, 'province_id' => 43, 'name' => 'Bumbaran'],
                ['id' => 830, 'province_id' => 43, 'name' => 'Butig'],
                ['id' => 831, 'province_id' => 43, 'name' => 'Calanogas'],
                ['id' => 832, 'province_id' => 43, 'name' => 'Ditsaan-Ramain'],
                ['id' => 833, 'province_id' => 43, 'name' => 'Ganassi'],
                ['id' => 834, 'province_id' => 43, 'name' => 'Kapai'],
                ['id' => 835, 'province_id' => 43, 'name' => 'Kapatagan'],
                ['id' => 836, 'province_id' => 43, 'name' => 'Lumba-Bayabao'],
                ['id' => 837, 'province_id' => 43, 'name' => 'Lumbaca-Unayan'],
                ['id' => 838, 'province_id' => 43, 'name' => 'Lumbatan'],
                ['id' => 839, 'province_id' => 43, 'name' => 'Lumbayanague'],
                ['id' => 840, 'province_id' => 43, 'name' => 'Madalum'],
                ['id' => 841, 'province_id' => 43, 'name' => 'Madamba'],
                ['id' => 842, 'province_id' => 43, 'name' => 'Maguing'],
                ['id' => 843, 'province_id' => 43, 'name' => 'Malabang'],
                ['id' => 844, 'province_id' => 43, 'name' => 'Marantao'],
                ['id' => 845, 'province_id' => 43, 'name' => 'Marogong'],
                ['id' => 846, 'province_id' => 43, 'name' => 'Masiu'],
                ['id' => 847, 'province_id' => 43, 'name' => 'Mulondo'],
                ['id' => 848, 'province_id' => 43, 'name' => 'Pagayawan'],
                ['id' => 849, 'province_id' => 43, 'name' => 'Piagapo'],
                ['id' => 850, 'province_id' => 43, 'name' => 'Poona Bayabao'],
                ['id' => 851, 'province_id' => 43, 'name' => 'Pualas'],
                ['id' => 852, 'province_id' => 43, 'name' => 'Saguiaran'],
                ['id' => 853, 'province_id' => 43, 'name' => 'Sultan Dumalondong'],
                ['id' => 854, 'province_id' => 43, 'name' => 'Picong'],
                ['id' => 855, 'province_id' => 43, 'name' => 'Tagoloan II'],
                ['id' => 856, 'province_id' => 43, 'name' => 'Tamparan'],
                ['id' => 857, 'province_id' => 43, 'name' => 'Taraka'],
                ['id' => 858, 'province_id' => 43, 'name' => 'Tubaran'],
                ['id' => 859, 'province_id' => 43, 'name' => 'Tugaya'],
                ['id' => 860, 'province_id' => 43, 'name' => 'Wao'],
                ['id' => 861, 'province_id' => 44, 'name' => 'Baybay City'],
                ['id' => 862, 'province_id' => 44, 'name' => 'Ormoc City'],
                ['id' => 863, 'province_id' => 44, 'name' => 'Tacloban City'],
                ['id' => 864, 'province_id' => 44, 'name' => 'Abuyog'],
                ['id' => 865, 'province_id' => 44, 'name' => 'Alangalang'],
                ['id' => 866, 'province_id' => 44, 'name' => 'Albuera'],
                ['id' => 867, 'province_id' => 44, 'name' => 'Babatngon'],
                ['id' => 868, 'province_id' => 44, 'name' => 'Barugo'],
                ['id' => 869, 'province_id' => 44, 'name' => 'Bato'],
                ['id' => 870, 'province_id' => 44, 'name' => 'Burauen'],
                ['id' => 871, 'province_id' => 44, 'name' => 'Calubian'],
                ['id' => 872, 'province_id' => 44, 'name' => 'Capoocan'],
                ['id' => 873, 'province_id' => 44, 'name' => 'Carigara'],
                ['id' => 874, 'province_id' => 44, 'name' => 'Dagami'],
                ['id' => 875, 'province_id' => 44, 'name' => 'Dulag'],
                ['id' => 876, 'province_id' => 44, 'name' => 'Hilongos'],
                ['id' => 877, 'province_id' => 44, 'name' => 'Hindang'],
                ['id' => 878, 'province_id' => 44, 'name' => 'Inopacan'],
                ['id' => 879, 'province_id' => 44, 'name' => 'Isabel'],
                ['id' => 880, 'province_id' => 44, 'name' => 'Jaro'],
                ['id' => 881, 'province_id' => 44, 'name' => 'Javier'],
                ['id' => 882, 'province_id' => 44, 'name' => 'Julita'],
                ['id' => 883, 'province_id' => 44, 'name' => 'Kananga'],
                ['id' => 884, 'province_id' => 44, 'name' => 'La Paz'],
                ['id' => 885, 'province_id' => 44, 'name' => 'Leyte'],
                ['id' => 886, 'province_id' => 44, 'name' => 'Macarthur'],
                ['id' => 887, 'province_id' => 44, 'name' => 'Mahaplag'],
                ['id' => 888, 'province_id' => 44, 'name' => 'Matag-ob'],
                ['id' => 889, 'province_id' => 44, 'name' => 'Matalom'],
                ['id' => 890, 'province_id' => 44, 'name' => 'Mayorga'],
                ['id' => 891, 'province_id' => 44, 'name' => 'Merida'],
                ['id' => 892, 'province_id' => 44, 'name' => 'Palo'],
                ['id' => 893, 'province_id' => 44, 'name' => 'Palompon'],
                ['id' => 894, 'province_id' => 44, 'name' => 'Pastrana'],
                ['id' => 895, 'province_id' => 44, 'name' => 'San Isidro'],
                ['id' => 896, 'province_id' => 44, 'name' => 'San Miguel'],
                ['id' => 897, 'province_id' => 44, 'name' => 'Santa Fe'],
                ['id' => 898, 'province_id' => 44, 'name' => 'Tabango'],
                ['id' => 899, 'province_id' => 44, 'name' => 'Tabontabon'],
                ['id' => 900, 'province_id' => 44, 'name' => 'Tanauan'],
                ['id' => 901, 'province_id' => 44, 'name' => 'Tolosa'],
                ['id' => 902, 'province_id' => 44, 'name' => 'Tunga'],
                ['id' => 903, 'province_id' => 44, 'name' => 'Villaba'],
                ['id' => 904, 'province_id' => 45, 'name' => 'Cotabato City'],
                ['id' => 905, 'province_id' => 45, 'name' => 'Ampatuan'],
                ['id' => 906, 'province_id' => 45, 'name' => 'Barira'],
                ['id' => 907, 'province_id' => 45, 'name' => 'Buldon'],
                ['id' => 908, 'province_id' => 45, 'name' => 'Buluan'],
                ['id' => 909, 'province_id' => 45, 'name' => 'Datu Abdullah Sangki'],
                ['id' => 910, 'province_id' => 45, 'name' => 'Datu Anggal Midtimbang'],
                ['id' => 911, 'province_id' => 45, 'name' => 'Datu Blah T. Sinsuat'],
                ['id' => 912, 'province_id' => 45, 'name' => 'Datu Hoffer Ampatuan'],
                ['id' => 913, 'province_id' => 45, 'name' => 'Datu Montawal'],
                ['id' => 914, 'province_id' => 45, 'name' => 'Datu Odin Sinsuat'],
                ['id' => 915, 'province_id' => 45, 'name' => 'Datu Paglas'],
                ['id' => 916, 'province_id' => 45, 'name' => 'Datu Piang'],
                ['id' => 917, 'province_id' => 45, 'name' => 'Datu Salibo'],
                ['id' => 918, 'province_id' => 45, 'name' => 'Datu Saudi-Ampatuan'],
                ['id' => 919, 'province_id' => 45, 'name' => 'Datu Unsay'],
                ['id' => 920, 'province_id' => 45, 'name' => 'Gen. S. K. Pendatun'],
                ['id' => 921, 'province_id' => 45, 'name' => 'Guindulungan'],
                ['id' => 922, 'province_id' => 45, 'name' => 'Kabuntalan'],
                ['id' => 923, 'province_id' => 45, 'name' => 'Mamasapano'],
                ['id' => 924, 'province_id' => 45, 'name' => 'Mangudadatu'],
                ['id' => 925, 'province_id' => 45, 'name' => 'Matanog'],
                ['id' => 926, 'province_id' => 45, 'name' => 'Northern Kabuntalan'],
                ['id' => 927, 'province_id' => 45, 'name' => 'Pagalungan'],
                ['id' => 928, 'province_id' => 45, 'name' => 'Paglat'],
                ['id' => 929, 'province_id' => 45, 'name' => 'Pandag'],
                ['id' => 930, 'province_id' => 45, 'name' => 'Parang'],
                ['id' => 931, 'province_id' => 45, 'name' => 'Rajah Buayan'],
                ['id' => 932, 'province_id' => 45, 'name' => 'Shariff Aguak'],
                ['id' => 933, 'province_id' => 45, 'name' => 'Shariff Saydona Mustapha'],
                ['id' => 934, 'province_id' => 45, 'name' => 'South Upi'],
                ['id' => 935, 'province_id' => 45, 'name' => 'Sultan Kudarat'],
                ['id' => 936, 'province_id' => 45, 'name' => 'Sultan Mastura'],
                ['id' => 937, 'province_id' => 45, 'name' => 'Sultan sa Barongis'],
                ['id' => 938, 'province_id' => 45, 'name' => 'Talayan'],
                ['id' => 939, 'province_id' => 45, 'name' => 'Talitay'],
                ['id' => 940, 'province_id' => 45, 'name' => 'Upi'],
                ['id' => 941, 'province_id' => 46, 'name' => 'Boac'],
                ['id' => 942, 'province_id' => 46, 'name' => 'Buenavista'],
                ['id' => 943, 'province_id' => 46, 'name' => 'Gasan'],
                ['id' => 944, 'province_id' => 46, 'name' => 'Mogpog'],
                ['id' => 945, 'province_id' => 46, 'name' => 'Santa Cruz'],
                ['id' => 946, 'province_id' => 46, 'name' => 'Torrijos'],
                ['id' => 947, 'province_id' => 47, 'name' => 'Masbate City'],
                ['id' => 948, 'province_id' => 47, 'name' => 'Aroroy'],
                ['id' => 949, 'province_id' => 47, 'name' => 'Baleno'],
                ['id' => 950, 'province_id' => 47, 'name' => 'Balud'],
                ['id' => 951, 'province_id' => 47, 'name' => 'Batuan'],
                ['id' => 952, 'province_id' => 47, 'name' => 'Cataingan'],
                ['id' => 953, 'province_id' => 47, 'name' => 'Cawayan'],
                ['id' => 954, 'province_id' => 47, 'name' => 'Claveria'],
                ['id' => 955, 'province_id' => 47, 'name' => 'Dimasalang'],
                ['id' => 956, 'province_id' => 47, 'name' => 'Esperanza'],
                ['id' => 957, 'province_id' => 47, 'name' => 'Mandaon'],
                ['id' => 958, 'province_id' => 47, 'name' => 'Milagros'],
                ['id' => 959, 'province_id' => 47, 'name' => 'Mobo'],
                ['id' => 960, 'province_id' => 47, 'name' => 'Monreal'],
                ['id' => 961, 'province_id' => 47, 'name' => 'Palanas'],
                ['id' => 962, 'province_id' => 47, 'name' => 'Pio V. Corpuz'],
                ['id' => 963, 'province_id' => 47, 'name' => 'Placer'],
                ['id' => 964, 'province_id' => 47, 'name' => 'San Fernando'],
                ['id' => 965, 'province_id' => 47, 'name' => 'San Jacinto'],
                ['id' => 966, 'province_id' => 47, 'name' => 'San Pascual'],
                ['id' => 967, 'province_id' => 47, 'name' => 'Uson'],
                ['id' => 968, 'province_id' => 48, 'name' => 'Caloocan City'],
                ['id' => 969, 'province_id' => 48, 'name' => 'Las Piñas City'],
                ['id' => 970, 'province_id' => 48, 'name' => 'Makati City'],
                ['id' => 971, 'province_id' => 48, 'name' => 'Malabon City'],
                ['id' => 972, 'province_id' => 48, 'name' => 'Mandaluyong City'],
                ['id' => 973, 'province_id' => 48, 'name' => 'Manila City'],
                ['id' => 974, 'province_id' => 48, 'name' => 'Marikina City'],
                ['id' => 975, 'province_id' => 48, 'name' => 'Muntinlupa City'],
                ['id' => 976, 'province_id' => 48, 'name' => 'Navotas City'],
                ['id' => 977, 'province_id' => 48, 'name' => 'Parañaque City'],
                ['id' => 978, 'province_id' => 48, 'name' => 'Pasay City'],
                ['id' => 979, 'province_id' => 48, 'name' => 'Pasig City'],
                ['id' => 980, 'province_id' => 48, 'name' => 'Quezon City'],
                ['id' => 981, 'province_id' => 48, 'name' => 'San Juan City'],
                ['id' => 982, 'province_id' => 48, 'name' => 'Taguig City'],
                ['id' => 983, 'province_id' => 48, 'name' => 'Valenzuela City'],
                ['id' => 984, 'province_id' => 48, 'name' => 'Pateros'],
                ['id' => 985, 'province_id' => 49, 'name' => 'Oroquieta City'],
                ['id' => 986, 'province_id' => 49, 'name' => 'Ozamiz City'],
                ['id' => 987, 'province_id' => 49, 'name' => 'Tangub City'],
                ['id' => 988, 'province_id' => 49, 'name' => 'Aloran'],
                ['id' => 989, 'province_id' => 49, 'name' => 'Baliangao'],
                ['id' => 990, 'province_id' => 49, 'name' => 'Bonifacio'],
                ['id' => 991, 'province_id' => 49, 'name' => 'Calamba'],
                ['id' => 992, 'province_id' => 49, 'name' => 'Clarin'],
                ['id' => 993, 'province_id' => 49, 'name' => 'Concepcion'],
                ['id' => 994, 'province_id' => 49, 'name' => 'Don Victoriano Chiongbian'],
                ['id' => 995, 'province_id' => 49, 'name' => 'Jimenez'],
                ['id' => 996, 'province_id' => 49, 'name' => 'Lopez Jaena'],
                ['id' => 997, 'province_id' => 49, 'name' => 'Panaon'],
                ['id' => 998, 'province_id' => 49, 'name' => 'Plaridel'],
                ['id' => 999, 'province_id' => 49, 'name' => 'Sapang Dalaga'],
                ['id' => 1000, 'province_id' => 49, 'name' => 'Sinacaban'],

            ]
        );
    }

}
